# .github/workflows/spaceship.yml
name: Version spaceship

on:
  pull_request:
    paths:
      - .github/workflows/spaceship.yml
      - spaceship/**
  push:
    paths:
      - .github/workflows/spaceship.yml
      - spaceship/**
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.5.4
        with:
          prefix: spaceship-
          log-path: spaceship/